### ISSUE TITLE
[Feature] data.sql 추가

### ISSUE THREAD

**Issue by 2eungwoo** [Kernel360/KBE5_DANMUJI_BE#204]
## 📌 기능 설명
- 현재 많은 엔티티들이 외래키 제약조건에 의해 테스트가 불편한 상황입니다.
- 따라서 스프링부트를 실행시키면 자동으로 값 삽입이 되도록 sql 정적 파일을 생성합니다.

## ✅ 해야 할 일
- [ ] sql 파일 생성
- [ ] yml 옵션 추가
```yml
spring:
  sql:
    init:
      mode: always  
  jpa:
    defer-datasource-initialization: true
```
